version: '3.8'

services:
  frontend:
    build:
      context: ./todofrontend
    ports:
      - "3001:5173"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./todobackend
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: 246472
      MYSQL_DATABASE: mydatabase
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 246472
      MYSQL_DATABASE: mydatabase
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s
networks:
  app-network:
    driver: bridge

volumes:
  db-data:

